### ISSUE TITLE
Refined difficulty system

### ISSUE THREAD

**Issue by museHD** [museHD/MineWalker#3]
I didn't have much experience with game development when I made the project so the values that I chose for difficulty settings were set arbitrarily through trial and error. These can be improved by using some sort of standard method for determining difficulty. Difficulty settings are contained here: https://github.com/museHD/MineWalker/blob/master/main.py#L103-L154

**Comment by justispm** [comment]
I'd like to try to take this on as my first Github project.  On line 5 you import Minewalker. Do you know how I would go about importing this? I get an error when trying to run your code, is there a PIP I need to install in order for this function? 

Thanks, hope I can be of some assistance!

**Comment by museHD** [comment]
Hi, great to see new open source contributors :)
When it imports minewalker, it imports the minewalker.py file that's in the repository so there is no need to install it via pip and it wouldn't work anyway because it's not a library. There are a few other libraries that I'm using...  You should be able to install those by _pip install -r requirements.txt _
Please send the specific error if you're still having trouble.

Thanks!

**Comment by justispm** [comment]
Glad to try and contribute and build up my skills! I got it running and have played several games and I enjoy it! 

Is the ideal behind this request for someone to go through and manually test the different difficulty settings and try through trial and error to find the best exposure time / number of "special abilities" (using "Q" to locate mines) to find the most reasonable setting for each difficulty? Sorry if this is a mundane question, I just want to make sure I understand the work to be done before I try to contribute! 

One thing I did notice is in the "readme" file it states that the objective of the game is to go from top left to bottom left, but the real goal of the game is to go from top left to bottom right!

**Comment by museHD** [comment]
Glad you got it working and enjoyed the game!

I read [this](https://en.wikipedia.org/wiki/Dynamic_game_difficulty_balancing#Approaches) Wikipedia article which mentions having some sort linear difficulty curve. Perhaps the parameters could be scaled using that difficulty curve. (I know it talks about score with respect to time, but a similar idea can be applied to difficulty.) 
To find what increments suit it the best, you might have to do some trial and error and figure out which one feels the best. I hope that clarifies the issue. Don't worry about asking additional questions!

Also, great pick up on that readme typo. Can you please create a [new issue](https://github.com/museHD/MineWalker/issues/new/choose) and make a PR to fix that? 

Thanks

**Comment by museHD** [comment]
It would be nice if we could also implement a Difficulty multiplier. Might want to have a discussion with @udaybadhe.
This could be useful in addressing #2 to make scores more accurate

**Comment by justispm** [comment]
Okay, sorry for the delayed response, work was a little hectic this week.  But I found another issue when testing the difficulty settings.  On line 231 of minewalker.py the statement "if powerups > 1:" actually ended up cutting off the power ups when 2 remained.  Therefore, to provide the proper amount of powerups for each difficulty setting I changed this to -1, which allows you to use the last two remaining powerups.  It will display "Remaining Scans: 0" when you are out of powerups, and if you attempt to use it again it will not work and will display "No Remaining Powerups!"

In regard to the primary request here, "Refined difficulty system" I am leaning towards a linear increase in difficulty for each setting.  Please let me know how you feel about this, but my idea is to increase board length with each setting, number of mines with each setting, display interval decreasing with each setting, and number of powerups decreasing with each setting of increased difficulty.  Perhaps towards the more difficult settings, the rate of increase will increase, so, for example the jump in board length for the initial 3 level's might be a jump of 1 in board length (as opposed to the initial setup where this remained constant), but for the more difficult settings it will increase by more, say 3, then 4, then 5.  

These are just ideas, I wanted to check with you @museHD before I submitted anything! Let me know what you think! I graphed each variable vs difficulty setting in excel to visualize the more linear progression and will utilize these graphs to fins the most linear increase in difficulty.  Maybe reserving "Extreme" and "Ultra Madness" for more extreme increases in difficulty that surpass the linear progression.

**Comment by museHD** [comment]
Hey @justispm,
 
no worries you can take your time :)

Great pickup on the powerups bug! Feel free to create a new [issue](https://github.com/museHD/MineWalker/issues/new/choose) for it and make a PR. 

As for the difficulty, what you said was pretty much I had in mind, except maybe jumps of 2 or 3 in the initial levels and then perhaps 4 or 5 in the ultimate ones. It would be great if you could share the graphs just so we can review them before you make changes.

Thank you very much for your help!
Let me know if I can clarify further 😄

**Comment by justispm** [comment]
[MineWalker Suggestions.xlsx](https://github.com/museHD/MineWalker/files/9285927/MineWalker.Suggestions.xlsx)
Let me know if you can't view this excel sheet, this is my first time trying to upload something like this, so may have done it wrong! But these are a rough linear increase in difficulty that I came up with.  I can refine it further if you feel it is necessary :).  Thank you so much for being so welcoming to the open source community.  This has been a joy as my first experience, so thank you so much and I hope to one day, once I develop more skills, to repay the favor :)

**Comment by museHD** [comment]
Hey @justispm,

Sorry for my late reply; I had exams going on.
However I did see your work and I'm very impressed!
What you have in the excel sheet was pretty much what I had in mind, so well done!
Could you make those changes and play a few rounds of each level to see how the game feels? And if it *feels* balanced enough, go ahead and create a PR for it :)

Also, I'm glad you enjoyed your first open source contribution. I hope you will continue to contribute to open source projects too!
If you have any suggestions or questions regarding this project, my other projects, or Open Source itself, feel free to reach out!

Thank you for your efforts and congratulations on your first contribution!
